name: "Peony CI (Twitter)"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * 5 # run actions on friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        # only need to test one version, as this test tries to find out if
        # Twitter's endpoints are still working as expected
        python-version: '3.12'
    - name: Install dependencies
      run: pip install --upgrade -r tests_requirements.txt
    - name: Run tests
      run: pytest tests
      env:
        PEONY_ACCESS_TOKEN: ${{ secrets.PEONY_ACCESS_TOKEN }}
        PEONY_ACCESS_TOKEN_SECRET: ${{ secrets.PEONY_ACCESS_TOKEN_SECRET }}
        PEONY_CONSUMER_KEY: ${{ secrets.PEONY_CONSUMER_KEY }}
        PEONY_CONSUMER_SECRET: ${{ secrets.PEONY_CONSUMER_SECRET }}
